### ISSUE TITLE
PI algo checklist

### ISSUE THREAD

**Issue by aremazeilles** [madrob-beast/madrob_beast_pi#13]
FYI, the list of items I am usually checking for validating a PI code:

 
- [x] 1. Readme available (purpose, install, use, acknowledgment)
- [x] 2. identify test files (input --> output)
- [x] 3. confirm main program structure (input, output)
- [ ] 4. check input-output file format
- [x] 5. insert docker generation files (TEC)
- [x] 6. insert CI process (TEC)
- [ ] 7. insert docker hub secret (TEC)
- [ ] 8. double check template spec again

I guess some are already solved in this case, correct @alfonsotecnalia
