### ISSUE TITLE
Beast hardware update ToDo list

### ISSUE THREAD

**Issue by Enri2077** [madrob-beast/madrob_beast_pi#17]
- [x] Implement disturbance from BMS:
  * [x] lut (like madrob)
  * [x] localization based torque bumps (when passing by a location in the testbed frame)
- [x] implement PIs
- [x] Implement localization (maybe AMCL if odom is good enough)
- [x] check data formats
- [ ] user manual
